name: JavaDoc

on:
  workflow_dispatch:

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate JavaDoc
        run: mvn javadoc:javadoc
      - name: Deploy JavaDoc
        uses: JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: target/site/apidocs
          target-folder: docs/${{ github.ref_name }}
          branch: gh-pages
