name: Publish JavaDoc

on:
  pull_request:
  push:
    branches: [ 7.0.X ]
  workflow_dispatch:

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Echo Java Version
        run:  java -version

      - name: Print Current workflow
        run: >
          cat .github/workflows/manual-javadoc.yml

      - name: Generate JavaDoc
        run: mvn clean javadoc:javadoc

      - name: Deploy JavaDoc
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: target/reports/apidocs
          target-folder: docs/${{ github.ref_name }}
          branch: gh-pages
