name: SerDe Compatibility Test

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }} SerDe Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: cpp
            name: C++
            profile: check_cpp_files
          - language: go
            name: Go
            profile: check_go_files
          - language: java
            name: Java
            profile: check_java_files
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Download ${{ matrix.name }} snapshots
        run: ./tools/download_serialization_test_data.sh ${{ matrix.language }}

      - name: Run Java tests against ${{ matrix.name }} snapshots
        run: mvn test -P ${{ matrix.profile }}
